# Generated by Django 5.1 on 2024-09-08 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookinfo_options_pepoleinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PepoleInfo',
            new_name='PeopleInfo',
        ),
        migrations.AlterModelTable(
            name='peopleinfo',
            table='peopleinfo',
        ),
    ]
