# Generated by Django 5.1 on 2024-09-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_rename_is_delecte_bookinfo_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='pub_data',
            field=models.DateField(null=True),
        ),
    ]
