# Generated by Django 5.1 on 2024-09-08 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_bookinfo_pub_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peopleinfo',
            old_name='is_delecte',
            new_name='is_delete',
        ),
    ]
