# Generated by Django 5.1 on 2024-09-09 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='MingCheng')),
                ('pub_date', models.DateField(null=True, verbose_name='faburiqi')),
                ('readcount', models.IntegerField(default=0, verbose_name='yueduliang')),
                ('commentcount', models.IntegerField(default=0, verbose_name='pinglunliang')),
                ('is_delete', models.BooleanField(default=False, verbose_name='luojishanchu')),
            ],
            options={
                'verbose_name': 'TuShu',
                'db_table': 'bookinfo',
            },
        ),
        migrations.CreateModel(
            name='PeopleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Renming')),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female')], default=0, verbose_name='xingbie')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='Miaoshu')),
                ('is_delete', models.BooleanField(default=False, verbose_name='luojishanchu')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookinfo', verbose_name='tushu')),
            ],
            options={
                'verbose_name': 'Renwuxinxi',
                'db_table': 'peopleinfo',
            },
        ),
    ]
